Vagrant.configure("2") do |config|
    # Especificar la caja de Ubuntu
    config.vm.box = "ubuntu/bionic64"
    
    # Configurar la máquina virtual
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    
    # Configurar la red
    config.vm.network "forwarded_port", guest: 80, host: 8080
    
    # Configurar la carpeta compartida
    config.vm.synced_folder "./html", "/var/www/html"
    
    # Script de configuración para instalar Apache
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
    SHELL
  end
  
  